require 'adminlte-rails'
require 'devise'
require 'carrierwave-aws'
require 'carrierwave/mongoid'
require 'font-awesome-rails'
require 'liquid'
require 'jquery-datatables-rails'
require 'jquery-rails'
require 'jquery-turbolinks'
require 'less-rails-bootstrap'
require 'mongoid'
require 'mongoid_slug'
require 'mongoid_rails_migrations'
# require 'pagedown-bootstrap-rails'
require 'redcarpet'
require 'turbolinks'
require 'hicube/engine'

module Hicube
end
